# Notebook 3: Individual Parks

The next step in our process was to scale down our analysis to the park level and examine CES servies offered by park. Since our methodology closely follows the Hale (2019) aricle, we needed to hand-code a select set of the tags into Hale's predefined CES buckets. To do this, we first coded the top 200 tags across all parks to get a sense of the types of services offered across all parks. The top 100 tags did not yield enough codeable tags, so we expanded that selection for a more robust sample. 

Tags themeselves are coded into one of the following categories (we did not cross-code, for parsimony, though we recognize that future analysis would yield more comprehensive results if tags could be cross-coded): existence, recreation, social relations, aesthetics, spritual, knowledge systems, inspiration, cultural heritage, education, sense of place, and culutral diversity. 

We coded parks that had at least 50 unique tags associated with that specific park. The coded parks are: MacArthur, Franklin Canyon, Hancock,Rio de Los Angeles, Runyon Canyon, Coldwater Creek, Cheviot Hills, and Angels Gate. We coded tags that fit into each of the above cateogories, but did not code tags that did not equate to a CES (i.e., nonsensical tags, vague tags, or tags for unidentifiable built infrastructure).

In [ ]:
#importing parks csv
import pandas as pd

# You might need to add a path as well
fn = 'parks_data.csv'
parks_data = pd.read_csv(fn)
parks_data.head()

In [ ]:
import nltk
import re
from nltk.tokenize import word_tokenize, sent_tokenize
from nltk.corpus import stopwords

swords = [re.sub(r"[^A-z\s]", "", sword) for sword in stopwords.words('english')]
swords += ['losangeles', 'la', 'losangelesca', 'ca', 'macarthur', 'macarthurpark', 'woodley', 'riodelosangeles', 'runyoncanyon', 
           'temescalgateway', 'heidelbergpark', 'hancockpark', 'franklincanyonpark', 'franklincanyonpark', 'angelsgate', 
           'coldwatercanyon', 'chatsworthparksouth','cheviothills', 'california', 'usa', 'southerncalifornia', 'park', 'parklabrea', 
          'unitedstates', 'america']

def clean_string(text):
    # remove punctuation
    text = re.sub(r"[^A-z\s]", "", text)
    
    cleaned_list_of_words = [word for word in word_tokenize(text.lower()) if word not in swords] #return a string or apply to all tags
    
    return cleaned_list_of_words

#calling the function to only apply to the tags column 
parks_data['tags'] = parks_data['tags'].apply(clean_string)

In [ ]:
parks_data
parks_data.parkname.unique()

### MacArthur Park

In [ ]:
#Need to figure out how to filter by parkname and retain the tags info by photo
macarthur = parks_data['parkname']=='macarthur'
macarthur.head()

In [ ]:
macarthur_tags = parks_data[macarthur]
print(macarthur_tags)
macarthur_tags.parkname.unique()

In [ ]:
cols = ['tags', 'parkname']
tag_park = macarthur_tags[cols].explode('tags', ignore_index=True)

In [ ]:
#create a column with count of each tag 
tag_park['value'] = [1] * tag_park.shape[0]

#return top 100 most used tags sorted by value
top_100_tags = tag_park.groupby('tags').sum().sort_values('value', ascending=False).head(100)

#so we can view all tags
pd.set_option('display.max_rows', 100)

print(top_100_tags)

In [ ]:
# exporting top 100 tags to a csv for hand coding 
top_100_tags.to_csv('top_tags_macarthur.csv', index=True)

# Analysis of spread of CES and strength of each CES - macarthur park

In [1]:
import pandas as pd

# import macarthur top tags
fn = 'top_tags_macarthur.csv'
macarthur_tags = pd.read_csv(fn)
macarthur_tags.head()

# import CES code breakdown for macarthur park
fn2 = 'codes_macarthur.csv'
macarthur_ces = pd.read_csv(fn2)
macarthur_ces.head()

,Words,Existence,Recreation,Social relations,Aesthetics,Spiritual,Knowledge systems,Inspiration,Cultural heritage,Education,Sense of place,Cultural diversity
0,westlake,173.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,lake,89.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,ciclavia,NaN,NaN,68.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,palmtrees,61.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,rally,NaN,NaN,53.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [2]:
# replace NaNs with 0

macarthur_ces.fillna(0)

,Words,Existence,Recreation,Social relations,Aesthetics,Spiritual,Knowledge systems,Inspiration,Cultural heritage,Education,Sense of place,Cultural diversity
0,westlake,173.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
1,lake,89.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
2,ciclavia,0.0,0.0,68.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
3,palmtrees,61.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
4,rally,0.0,0.0,53.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
5,palms,41.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
6,neighborhood,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,41.0,0.0
7,community,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,41.0,0.0
8,mexican,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,38.0
9,protest,0.0,0.0,37.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
10,lengua,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,36.0
11,keepfamliestogethor,0.0,0.0,36.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
12,tamale,0.0,0.0,36.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
13,asada,0.0,0.0,36.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
14,alpastor,0.0,0.0,36.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
15,march,0.0,0.0,36.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,36.0
16,migrant,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
17,carnitas,0.0,0.0,36.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
18,eltaurino,0.0,0.0,36.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
19,burrito,0.0,0.0,36.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
20,thegreattacohunt,0.0,0.0,36.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
21,immigration,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,36.0
22,landmark,0.0,0.0,0.0,0.0,0.0,0.0,0.0,34.0,0.0,0.0,0.0
23,monument,0.0,0.0,0.0,0.0,0.0,0.0,0.0,32.0,0.0,0.0,0.0
24,elks,32.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
25,parkplaza,32.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
26,heartofla,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,31.0,0.0
27,lasantacon,0.0,0.0,30.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
28,art,0.0,0.0,0.0,0.0,0.0,0.0,29.0,0.0,0.0,0.0,0.0
29,music,0.0,27.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
30,colorful,0.0,0.0,0.0,25.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
31,curlettandbeelman,0.0,0.0,0.0,0.0,0.0,0.0,0.0,24.0,0.0,0.0,0.0
32,portraitsofhope,0.0,0.0,0.0,0.0,0.0,0.0,24.0,0.0,0.0,0.0,0.0
33,publicart,0.0,0.0,0.0,0.0,0.0,0.0,23.0,0.0,0.0,0.0,0.0
34,people,0.0,0.0,23.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
35,bikes,0.0,22.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
36,signs,0.0,0.0,0.0,0.0,20.0,0.0,0.0,0.0,0.0,0.0,0.0
37,tacos,0.0,0.0,19.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
38,sanity,0.0,0.0,0.0,0.0,17.0,0.0,0.0,0.0,0.0,0.0,0.0
39,fortmacarthur,0.0,0.0,0.0,0.0,0.0,0.0,0.0,16.0,0.0,0.0,0.0
40,warreinactment,0.0,0.0,0.0,0.0,0.0,0.0,0.0,15.0,0.0,0.0,0.0
41,lilihaydn,0.0,15.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
42,bicycles,0.0,15.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
43,violin,0.0,15.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
44,birds,15.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
45,food,0.0,0.0,13.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
46,ciclovia,0.0,13.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
47,event,0.0,12.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
48,loslobos,0.0,12.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
49,palmtree,12.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
50,hollywood,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
51,bicyclists,0.0,11.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0

1. group by CES and count size
2. assign to new df to visualize

In [ ]:
macarthur_ces.dtypes

In [ ]:
# get list of columns from the original dataframe, excluding the ones that aren't about ces
cols = [col for col in macarthur_ces.columns if col not in ['Words']]

# normalize the data by dividing each column by the total tag counts (1682)
for col in cols:
    macarthur_ces[col] = macarthur_ces[col].sum()
    
ces = macarthur_ces[cols]/1682*100
print(ces)

Having trouble getting overall percentage for each group --> trying a different approach

In [8]:
#drop words column
macarthur_ces.drop(columns=['Words'])

#sum of each ces
sum_ces = macarthur_ces.sum(axis=0)
print(sum_ces)

Words                 westlakelakeciclaviapalmtreesrallypalmsneighbo...
Existence                                                         455.0
Recreation                                                        142.0
Social relations                                                  567.0
Aesthetics                                                         25.0
Spiritual                                                          37.0
Knowledge systems                                                   0.0
Inspiration                                                        76.0
Cultural heritage                                                 121.0
Education                                                           0.0
Sense of place                                                    113.0
Cultural diversity                                                146.0
dtype: object

In [15]:
# convert series to dataframe and keep index
# https://www.geeksforgeeks.org/convert-given-pandas-series-into-a-dataframe-with-its-index-as-another-column-on-the-dataframe/

cesDf = sum_ces.to_frame().reset_index()
print(cesDf)
list(cesDf.columns)

                 index                                                  0
0                Words  westlakelakeciclaviapalmtreesrallypalmsneighbo...
1            Existence                                              455.0
2           Recreation                                              142.0
3     Social relations                                              567.0
4           Aesthetics                                               25.0
5            Spiritual                                               37.0
6    Knowledge systems                                                0.0
7          Inspiration                                               76.0
8    Cultural heritage                                              121.0
9            Education                                                0.0
10      Sense of place                                              113.0
11  Cultural diversity                                              146.0

['index', 0]

In [16]:
cols = [col for col in macarthur_ces.columns if col not in ['index']]

ces_total = cesDf[cols]/1682*100
print(ces_total)

KeyError: "None of [Index(['Words', 'Existence', 'Recreation', 'Social relations', 'Aesthetics',\n       'Spiritual', 'Knowledge systems', 'Inspiration', 'Cultural heritage',\n       'Education', 'Sense of place', 'Cultural diversity'],\n      dtype='object')] are in the [columns]"

# rename columns
cesDf.columns=['ces','total']
print(cesDf)

In [14]:
#clean up df by droping row 0 and renaming columns

#drop row by index
cesDf.drop(labels=["Words"],axis=0,inplace=False)
print(cesDf)

KeyError: "['Words'] not found in axis"

In [ ]:
#divide each column by total tag counts 1682 and multiply by 100 to normalize the data

### Woodley Park

In [ ]:
#Need to figure out how to filter by parkname and retain the tags info by photo
woodley = parks_data['parkname']=='woodley'
woodley.head()

In [ ]:
woodley_tags = parks_data[woodley]
print(woodley_tags)
woodley_tags.parkname.unique()

In [ ]:
cols = ['tags', 'parkname']
tag_park = woodley_tags[cols].explode('tags', ignore_index=True)

In [ ]:
#create a column with count of each tag 
tag_park['value'] = [1] * tag_park.shape[0]

#return top 100 most used tags sorted by value
top_100_tags = tag_park.groupby('tags').sum().sort_values('value', ascending=False).head(100)

#so we can view all tags
pd.set_option('display.max_rows', 100)

print(top_100_tags)

In [ ]:
# exporting top 100 tags to a csv for hand coding 
top_100_tags.to_csv('top_tags_woodley.csv', index=True)

### Rio de Los Angeles

In [ ]:
#Need to figure out how to filter by parkname and retain the tags info by photo
riodelosangeles = parks_data['parkname']=='riodelosangeles'
riodelosangeles.head()

In [ ]:
riodelosangeles_tags = parks_data[riodelosangeles]
print(riodelosangeles_tags)
riodelosangeles_tags.parkname.unique()

In [ ]:
cols = ['tags', 'parkname']
tag_park = riodelosangeles_tags[cols].explode('tags', ignore_index=True)

In [ ]:
#create a column with count of each tag 
tag_park['value'] = [1] * tag_park.shape[0]

#return top 100 most used tags sorted by value
top_100_tags = tag_park.groupby('tags').sum().sort_values('value', ascending=False).head(100)

#so we can view all tags
pd.set_option('display.max_rows', 100)

print(top_100_tags)

In [ ]:
# exporting top 100 tags to a csv for hand coding 
top_100_tags.to_csv('top_tags_riodelosangeles.csv', index=True)

### Runyon Canyon

In [ ]:
#Need to figure out how to filter by parkname and retain the tags info by photo
runyoncanyon = parks_data['parkname']=='runyoncanyon'
runyoncanyon.head()

In [ ]:
runyoncanyon_tags = parks_data[runyoncanyon]
print(runyoncanyon_tags)
runyoncanyon_tags.parkname.unique()

In [ ]:
cols = ['tags', 'parkname']
tag_park = runyoncanyon_tags[cols].explode('tags', ignore_index=True)

In [ ]:
#create a column with count of each tag 
tag_park['value'] = [1] * tag_park.shape[0]

#return top 100 most used tags sorted by value
top_100_tags = tag_park.groupby('tags').sum().sort_values('value', ascending=False).head(100)

#so we can view all tags
pd.set_option('display.max_rows', 100)

print(top_100_tags)

In [ ]:
# exporting top 100 tags to a csv for hand coding 
top_100_tags.to_csv('top_tags_runyoncanyon.csv', index=True)

### Temescal Gateway

In [ ]:
#Need to figure out how to filter by parkname and retain the tags info by photo
temescalgateway = parks_data['parkname']=='temescalgateway'
temescalgateway.head()

In [ ]:
temescalgateway_tags = parks_data[temescalgateway]
print(temescalgateway_tags)
temescalgateway_tags.parkname.unique()

In [ ]:
cols = ['tags', 'parkname']
tag_park = temescalgateway_tags[cols].explode('tags', ignore_index=True)

In [ ]:
#create a column with count of each tag 
tag_park['value'] = [1] * tag_park.shape[0]

#return top 100 most used tags sorted by value
top_100_tags = tag_park.groupby('tags').sum().sort_values('value', ascending=False).head(100)

#so we can view all tags
pd.set_option('display.max_rows', 100)

print(top_100_tags)

In [ ]:
# exporting top 100 tags to a csv for hand coding 
top_100_tags.to_csv('top_tags_temescalgateway.csv', index=True)

### Heidelberg Park

### Hancock Park

In [ ]:
#Need to figure out how to filter by parkname and retain the tags info by photo
hancockpark = parks_data['parkname']=='hancockpark'
hancockpark.head()

In [ ]:
hancockpark_tags = parks_data[hancockpark]
print(hancockpark_tags)
hancockpark_tags.parkname.unique()

In [ ]:
cols = ['tags', 'parkname']
tag_park = hancockpark_tags[cols].explode('tags', ignore_index=True)

In [ ]:
#create a column with count of each tag 
tag_park['value'] = [1] * tag_park.shape[0]

#return top 100 most used tags sorted by value
top_100_tags = tag_park.groupby('tags').sum().sort_values('value', ascending=False).head(100)

#so we can view all tags
pd.set_option('display.max_rows', 100)

print(top_100_tags)

In [ ]:
# exporting top 100 tags to a csv for hand coding 
top_100_tags.to_csv('top_tags_hancockpark.csv', index=True)

### Franklin Canyon Park

In [ ]:
#Need to figure out how to filter by parkname and retain the tags info by photo
franklincanyonpark = parks_data['parkname']=='franklincanyonpark'
franklincanyonpark.head()

In [ ]:
franklincanyonpark_tags = parks_data[franklincanyonpark]
print(franklincanyonpark_tags)
franklincanyonpark_tags.parkname.unique()

In [ ]:
cols = ['tags', 'parkname']
tag_park = franklincanyonpark_tags[cols].explode('tags', ignore_index=True)

In [ ]:
#create a column with count of each tag 
tag_park['value'] = [1] * tag_park.shape[0]

#return top 100 most used tags sorted by value
top_100_tags = tag_park.groupby('tags').sum().sort_values('value', ascending=False).head(100)

#so we can view all tags
pd.set_option('display.max_rows', 100)

print(top_100_tags)

In [ ]:
# exporting top 100 tags to a csv for hand coding 
top_100_tags.to_csv('top_tags_franklincanyonpark.csv', index=True)

### Angels Gate

In [ ]:
#Need to figure out how to filter by parkname and retain the tags info by photo
angelsgate = parks_data['parkname']=='angelsgate'
angelsgate.head()

In [ ]:
angelsgate_tags = parks_data[angelsgate]
print(angelsgate_tags)
angelsgate_tags.parkname.unique()

In [ ]:
cols = ['tags', 'parkname']
tag_park = angelsgate_tags[cols].explode('tags', ignore_index=True)

In [ ]:
#create a column with count of each tag 
tag_park['value'] = [1] * tag_park.shape[0]

#return top 100 most used tags sorted by value
top_100_tags = tag_park.groupby('tags').sum().sort_values('value', ascending=False).head(100)

#so we can view all tags
pd.set_option('display.max_rows', 100)

print(top_100_tags)

In [ ]:
# exporting top 100 tags to a csv for hand coding 
top_100_tags.to_csv('top_tags_angelsgate.csv', index=True)

### Coldwater Canyon

In [ ]:
#Need to figure out how to filter by parkname and retain the tags info by photo
coldwatercanyon = parks_data['parkname']=='coldwatercanyon'
coldwatercanyon.head()

In [ ]:
coldwatercanyon_tags = parks_data[coldwatercanyon]
print(coldwatercanyon_tags)
coldwatercanyon_tags.parkname.unique()

In [ ]:
cols = ['tags', 'parkname']
tag_park = coldwatercanyon_tags[cols].explode('tags', ignore_index=True)

In [ ]:
#create a column with count of each tag 
tag_park['value'] = [1] * tag_park.shape[0]

#return top 100 most used tags sorted by value
top_100_tags = tag_park.groupby('tags').sum().sort_values('value', ascending=False).head(100)

#so we can view all tags
pd.set_option('display.max_rows', 100)

print(top_100_tags)

In [ ]:
# exporting top 100 tags to a csv for hand coding 
top_100_tags.to_csv('top_tags_coldwatercanyon.csv', index=True)

### Cheviot Hills

In [ ]:
#Need to figure out how to filter by parkname and retain the tags info by photo
cheviothills = parks_data['parkname']=='cheviothills'
cheviothills.head()

In [ ]:
cheviothills_tags = parks_data[cheviothills]
print(cheviothills_tags)
cheviothills_tags.parkname.unique()

In [ ]:
cols = ['tags', 'parkname']
tag_park = cheviothills_tags[cols].explode('tags', ignore_index=True)

In [ ]:
#create a column with count of each tag 
tag_park['value'] = [1] * tag_park.shape[0]

#return top 100 most used tags sorted by value
top_100_tags = tag_park.groupby('tags').sum().sort_values('value', ascending=False).head(100)

#so we can view all tags
pd.set_option('display.max_rows', 100)

print(top_100_tags)

In [ ]:
# exporting top 100 tags to a csv for hand coding 
top_100_tags.to_csv('top_tags_cheviothills.csv', index=True)

### Chatsworth Park South